services:
  frontend:
    container_name: ${PROJECT_NAME}-frontend
    image: ${REGISTRY}/${PROJECT_NAME}-frontend:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - ALLOWED_HOSTS=${DOMAIN}
    networks:
      - caddy_proxy_net
    labels:
      caddy: ${DOMAIN}
      caddy_network: caddy_proxy_net
      caddy.import: cloudflare_tls
      caddy.reverse_proxy: "{{upstreams 3000}}"

networks:
  caddy_proxy_net:
    external: true
    name: caddy_proxy_net