services:
  frontend:
    container_name: ${PROJECT_NAME}-frontend
    image: ${PROJECT_NAME}-frontend-dev:latest
    build:
      context: .
      target: development
    restart: unless-stopped
    environment:
      - ALLOWED_HOSTS=${DOMAIN}
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - global_dev_net
    labels:
      caddy: ${DOMAIN}
      caddy_network: global_dev_net
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 3000}}"

networks:
  global_dev_net:
    external: true
    name: global_dev_net